name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: disable tty in docker
      run: echo "::set-env name=DOCKER_FLAGS::"
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: test with gcc
      run: make docker_test_gcc
    - name: test with clang
      run: make docker_test_clang
    - name: test with valgrind
      run: make docker_test_valgrind
    - name: test release build
      run: make docker_test_release
